### ISSUE TITLE
There is no possibility to choose the color of the metric

### ISSUE THREAD

**Issue by newuan** [grafana/piechart-panel#105]
Grafana version 4.6.0
grafana-piechart-panel-11b21df
Actual:
![piechart](https://user-images.githubusercontent.com/29709952/32097853-88ddaf64-bb13-11e7-8104-984650c896e6.png)

Must be:
![must](https://user-images.githubusercontent.com/29709952/32097957-d140a82e-bb13-11e7-8415-6459b6f09f08.png)

**Comment by eastcirclek** [comment]
I also suffer from this issue; I cannot choose color. It did work but at some point it breaks.

**Comment by Ijin08** [comment]
Color-picker should work with latest release. But you need latest Grafana.
