### ISSUE TITLE
Can't view right side legend

### ISSUE THREAD

**Issue by selli96** [grafana/piechart-panel#116]
I'm using the latest version of grafana and i can't view legend on the right side: 

![image](https://user-images.githubusercontent.com/33827401/34572669-4100ebb2-f172-11e7-91b5-a9f3d5178927.png)

It seems that remains under the graph as follows:

![image2](https://user-images.githubusercontent.com/33827401/34573374-4c16899c-f174-11e7-8d61-c930f3aad6c1.png)

On and under graph legends work correctly.
I see this same bug on the latest versions of Chrome, Firefox, IE, and Edge on a Windows machine.

**Comment by remcopoelstra** [comment]
I also ran into this issue, I think it's due to some missing css rules in the current grafana master branch. I copied the .graph-legend-rightside css rules from the 4.6.x branch back to public/sass/components/_panel_graph.scss and this fixed the problem for me.

**Comment by selli96** [comment]
This fix my problem, thanks a lot.
