### ISSUE TITLE
"no data points" in grafana 5.0

### ISSUE THREAD

**Issue by Stephanium** [grafana/piechart-panel#119]
What Grafana version are you using?
5.0

What datasource are you using?
simple sql

What OS are you running grafana on?
windows 10

What did you do?
I import the dashboard from grafana4.6.3(the pie chart works perfectly fine in this version)

What happened?
on the panel it shows "no data points"
![image](https://user-images.githubusercontent.com/32287319/35318273-88a63e4c-0115-11e8-94a2-28e30530c64c.png)

![image](https://user-images.githubusercontent.com/32287319/35318347-d6324c50-0115-11e8-9400-1fee5a4460a1.png)

And I've tried both pie chart versions on grafana lab and on github but it turned out the same result.

**Comment by torkelo** [comment]
just published a new version that should work better in v5
