### ISSUE TITLE
Pie Chart Legend "Right side" on Grafana 5.0

### ISSUE THREAD

**Issue by micelshima** [grafana/piechart-panel#121]
In Grafana 5 BETA, when choosing in Pie Chart Options > Legend >Right Side position, Legend does not show

**Comment by torkelo** [comment]
just published a new version that should work better in v5

**Comment by micelshima** [comment]
I am sorry to say that it has gone worse, now balloontip says "invalid dimension for plot" and shows no pie chart at all

**Comment by GedPL** [comment]
@torkelo 
Which version of Pie Chart do you mean ? 1.2.0 ?
If yes - still cannot see legend when position is Right Side or Under Graph
![image](https://user-images.githubusercontent.com/31762538/36202243-47140666-1183-11e8-992f-d0f74c4e7d1c.png)

**Comment by micelshima** [comment]
Hi, it is working now.
Now the legend that doesn't show well is the 'Under graph' (see screenshot)

I can resize the box and it fixes, then save the dashboard and the next time I open it it is wrong again.

![screenshot - 14_02_2018 15_48_47](https://user-images.githubusercontent.com/10197970/36210477-ca229408-119e-11e8-9991-9e11dede4d72.png)

**Comment by GedPL** [comment]
Hi,

Grafana: 5.0.0-beta4
Pie chart: 1.20

Looks like Combine option doesn't affect legend at all and no scroll bar is shown when needed.
![image](https://user-images.githubusercontent.com/31762538/36666303-7097635a-1aea-11e8-8d3b-326156662e81.png)

Additiionally would be great to have Combine option type for selection as described here (not only by percentage).
https://github.com/grafana/piechart-panel/issues/120

Thank you !

**Comment by deto1986** [comment]
Grafana 5.0.0 (commit: af6e283)
PieChart: 1.2.0

Position Right side not working correctly. Sometimes it's there, sometimes not. Position 'Under graph' not rendered correctly when Pie Chart is at 'small' or 'medium' scale.

Also the 'Percentage Decimals' doesn't have any effect.

**Comment by skemena** [comment]
SOLVED:
i had the same problem.

updated my ubuntu to latest patchlevel. 
now it works correctly as before :)


![2018-03-07_085701](https://user-images.githubusercontent.com/37105971/37080340-ce26f2a2-21dd-11e8-86cd-8782551bcfd3.jpg)

**Comment by GedPL** [comment]
Same as deto1986 wrote.
OS vendor:            Red Hat Enterprise Linux 6
Patch level           2017.3.0
Grafana 5.0.1
