### ISSUE TITLE
Singlestat Unique count issue

### ISSUE THREAD

**Issue by ThuyLeVn** [grafana/piechart-panel#127]
We have total 12 different indexes for Elasticsearch Data source.
I want to show it in Singlestat
But is is wrong answer
 
![image](https://user-images.githubusercontent.com/24593553/36599317-54a79260-18af-11e8-93b1-f6f3299da63f.png)
 
and
![image](https://user-images.githubusercontent.com/24593553/36599334-5f839da0-18af-11e8-9422-3042a9e7d65b.png)

I tested with a lot of other cases (containers, tags, fields....) they had the same problem.
Do you know why?

Thanks
ThuyLe

**Comment by marefr** [comment]
Please create issue for singlestat in grafana main repository: https://github.com/grafana/grafana
