### ISSUE TITLE
Disastrous update after moving to 5.0.0 and then worse when updating plugin to 1.2.0

### ISSUE THREAD

**Issue by GalenOfTheShadows** [grafana/piechart-panel#129]
We recently update to 5.0.0 with the plugin at 1.1.4 and noticed that the legends were no longer rendering properly. When "On graph" was selected, the color of the text matches the color of the section of the chart, making the legend mostly unreadable, even on donut. Selecting "Under graph" places the legend so far off the panel only the top two rows of pixels from the legend can be seen, no matter how much the panel was resized. When selecting "Right side" the legend remained under the graph with the same aforementioned issue.

After updating the plugin to 1.2.0, the panel completely fails to render now, Grafana complaining: "Invalid dimensions for plot, width = 0, height = 152" this is on both old pie charts and freshly created charts on completely new dashboards. No matter what size the panel is scaled to, the numbers never change and Grafana refuses to render anything from the chart onto the panel.

**Comment by raidsec** [comment]
I could follow you when i try to do the same. grafana 5 will only work with 1.2.0 for me also. but 1.2.0 and the pie chart creating huge problems with the scroll bars. Maybe remove your piecharts plugin and reinstall it could be a solution

**Comment by GalenOfTheShadows** [comment]
Actually, it seems it might have been something with browser caching. I had to reboot the workstation (unrelated) and when I logged back in, the graph was completely fixed. So based on that, I'm pretty sure I had some stuck JSON that wasn't getting refreshed from the server even with a manual cache flush.

**Comment by GalenOfTheShadows** [comment]
Pretty sure it's not deve related, so closing.
