### ISSUE TITLE
Missing legend on load

### ISSUE THREAD

**Issue by cross** [grafana/piechart-panel#137]
I have pie-chart 1.2.0 panels in grafana master (5.1.0-pre).  When I add a panel for a metric across multple variable values, with the legend on the right, it displays correctly.  If I then duplicate that panel, and configure the duplicate to repeat for the variable ($team), this also displays correctly, but if more than one or two teams are selected, having the legend on the right makes the pie basically non-existent.

![screen shot 2018-03-16 at 14 10 00](https://user-images.githubusercontent.com/102556/37537609-7e6fab3e-2924-11e8-8b94-c57d92a971c7.png)

So, I switch the repeating panel legend to "Under graph".  This causes two separate problems, which I'll report in one issue unless asked to separate them.

1. The initial pie chart panel now loses it's legend completely.
    - Opening edit on this panel and turning the "Show legend" off and back on makes it reappear.  The pie shifts slightly right when the option is turned off, then substantially to the left when the legend reappears.
2. The repeating panels have two problems
    1. The pie is large enough to fall behind the legend displayed under the graph
        -  If I open the "Edit" for any panel in the dashboard, make no changes, and close that edit, or possibly other refresh actions, shrinks the pie down to almost but not quite small enough to fit above the legend.
    2. The legend rolls off of the bottom of the panel.  Only the first 2-3 (of 6-8) lines of the legend are displayed.

![screen shot 2018-03-16 at 14 23 00](https://user-images.githubusercontent.com/102556/37537973-a14e71de-2925-11e8-98e7-094a99b2816d.png)

Are there options I'm failing to configure?  Let me know if you want any more information.

**Comment by Didainius** [comment]
Noticing that on 5 as well.

**Comment by shehrozeee** [comment]
Same issue here too after upgrading to 5

**Comment by cross** [comment]
Seems to be resolved in grafana 5.2.x with pie-chart 1.3.3.  Thanks.
