### ISSUE TITLE
Pie Chart with MySQL datasource

### ISSUE THREAD

**Issue by sergey-chekanov** [grafana/piechart-panel#142]
Hi,

I want to create simple Pie Chart with MySQL datasource.

I use two simple querys:
`SELECT SUM(amount) as Monthly FROM tblhosting WHERE domainstatus = 'active' and billingcycle = 'Monthly';`
`SELECT SUM(amount)/12 as Annually FROM tblhosting WHERE domainstatus = 'active' and billingcycle = 'Annually';`

When I try create Table with this querys it works fine.
But when try the same with “Pie Chart” I got error:
`undefined is not an object (evaluating 'this.datapoints.length')`

Query Inspector:
```
xhrStatus:“complete”
request:Object
method:“POST”
url:“api/tsdb/query”
data:Object
from:“1525941113670”
to:“1525962713671”
queries:Array[2]
response:Object
results:Object
A:Object
refId:“A”
meta:Object
rowCount:1
sql:“SELECT SUM(amount) as Monthly FROM tblhosting WHERE domainstatus = ‘active’ and billingcycle = ‘Monthly’;”
series:null
tables:Array[1]
B:Object
refId:“B”
meta:Object
rowCount:1
sql:“SELECT SUM(amount)/12 as Annually FROM tblhosting WHERE domainstatus = ‘active’ and billingcycle = ‘Annually’;”
series:null
tables:Array[1]
0:Object
```

![6d733f03e74c20abb1bd42748310bd0ef49629d1_1_690x298](https://user-images.githubusercontent.com/7688234/39923743-912fede4-552d-11e8-88f2-aa32fa768848.png)
![1111](https://user-images.githubusercontent.com/7688234/39923744-915f41f2-552d-11e8-889c-75a21b9b4b79.png)

**Comment by scaarup** [comment]
Same here!

**Comment by Bruce-li-92** [comment]
same question

**Comment by xupeng** [comment]
Same here, too!

**Comment by dimatha** [comment]
+1

**Comment by marefr** [comment]
The piechart panel only works with time series data which means that you'll need to select a time_sec column in your query for the time - you should be able to use now() to return the same time for all your rows .

**Comment by itayB** [comment]
Does anyone succeed? trying to do it as a fake time series as @marefr suggest with no lack.
Can you show the desired expected json (from inspecting the HTTP response)? or provide an example of SQL Query (and related schema)?

Thanks!

**Comment by marefr** [comment]
@itayB will provide an example, but recommend you to have a look at 
Grafana's [community site](https://community.grafana.com/) which is more suitable for questions. 

Using latest Grafana (5.3-pre1)

```sql
SELECT
  now() as time_sec,
  count(value),
  measurement
FROM 
  grafana_metric
GROUP BY 3
```

Generates the following without any other options specified:

![image](https://user-images.githubusercontent.com/1668778/43064071-291d0af6-8e5e-11e8-87ba-79b9834c8f23.png)

**Comment by northtree** [comment]
My SQL solution for grouping.

`
SELECT
  NOW() as time_sec,
  pie.cnt as value,
  CONVERT(pie.category, char) as metric
FROM (
  SELECT 
    `your_col` as category, 
    count(id) AS cnt
  FROM `your_table`
  GROUP BY `your_col`
) as pie
GROUP BY pie.category
`

**Comment by dinggege1024** [comment]
LGTM
