### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/piechart-panel#145]
The sorting function on the Legends doesn't working.

![20180522150510](https://user-images.githubusercontent.com/2911588/40364888-a4faf2e8-5dd3-11e8-9889-fd954a7fb038.png)

~~~
Grafana v5.1.3 (commit: 087143285)
InfluxDB v1.5
Pie Chart 1.3.1
~~~

**Comment by deafwolf** [comment]
The same to me. It looks like display problem, if sorts then clicks a link, another link will be disabled.

Grafana v5.1.3
MySQL 5.7.21
Pie Chart 1.3.1

**Comment by cypressious** [comment]
![grafik](https://user-images.githubusercontent.com/1191816/40915197-70f5fd30-67fb-11e8-992e-0b9117085f71.png)

Same problem here. The sorting is somehow broken

**Comment by FUSAKLA** [comment]
Same here 
Grafana 5.1.3
Prometheus 2.2.1
Pie chart 1.3.1

on pie chart 1.3.0 works fine

**Comment by ilsonbaltazar** [comment]
This graphic doesn't accept values null. When some metric return null, the graph brakes. Doesn't It have a option to set null as zero?
