### ISSUE TITLE
Pie Chart Render not showing Legend properly

### ISSUE THREAD

**Issue by fatalglitch** [grafana/piechart-panel#151]
What Grafana version are you using? - v5.1.4

What datasource are you using? - Elasticsearch

What OS are you running grafana on? - Linux

What did you do? - piechart render

What was the expected result?- piechart render with legend on the right side

What happened instead? - piechart render with no legend

If related to metric query / data viz:

When running a render URL against an existing Pie Chart, the resulting PNG does not have the legend showing up properly. It appears to drop to the bottom right most section, and then not be visible.

Reproducable by creating a pie chart viz, marking it to show the legend, and then running the render URL call:

https://my.grafana.com/render/d-solo/000000096/_?from=now-1h%2Fd&height=500&panelId=8&theme=dark&to=now-5m&width=1000

**Comment by fatalglitch** [comment]
This is still occurring in 5.3.4 of Grafana with 1.3.3 of the piechart-panel, any update on this?

**Comment by torkelo** [comment]
issue with phantomjs, can be solved by using our new image rendering plugin instead that uses headless chrome. 

Required nodejs & yarn & yarn install, 
https://github.com/grafana/grafana-image-renderer

**Comment by Tetraneon** [comment]
Hi,

My config:
- Ubuntu 16.04
- Grafana 5.4.2
- nodejs v8.15 and yarn were installed

Instead having a error message after a LONG time, i have immediatly the message : "Rendering failed."

Logs : 
`t=2019-01-02T16:30:30+0100 lvl=eror msg="Rendering failed." logger=context userId=3 orgId=3 uname=XXXXX error="Rendering failed: Error: Failed to launch chrome!\n/usr/share/grafana/public/app/plugins/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
`

And now, I have this message with all charts...

**Comment by Tetraneon** [comment]
Hi guys,
I don't know when or how but it works now.
Many thanks !

**Comment by fatalglitch** [comment]
Ours now seems to "magically" be working as well. I'm assuming the phantomjs dependencies are pulled from a 3rd party source, and that bug was fixed. I'm marking this resolved/closed at this point.
