### ISSUE TITLE
Pie Chart not rendered

### ISSUE THREAD

**Issue by andreapozz** [grafana/piechart-panel#153]
The pie chart is not rendered when a dashboard refresh. A grid as in the image below is showed instead of the pie chart.
![schermata 2018-07-06 alle 14 31 34](https://user-images.githubusercontent.com/25820530/42378920-541e4b1c-8129-11e8-9511-bdc7749d6d41.png)

**Comment by marefr** [comment]
What Grafana version? What pie chart panel version? Please include your panel json/dashboard json for further assistance.

**Comment by andreapozz** [comment]
Grafana v5.2.1
Pie Chart v 1.3.3

`{
	"aliasColors": {},
	"breakPoint": "50%",
	"cacheTimeout": null,
	"combine": {
		"label": "Others",
		"threshold": 0
	},
	"datasource": "Retail Face",
	"fontSize": "80%",
	"format": "none",
	"gridPos": {
		"h": 9,
		"w": 12,
		"x": 11,
		"y": 11
	},
	"id": 18,
	"interval": null,
	"legend": {
		"percentage": true,
		"show": true,
		"values": false
	},
	"legendType": "Right side",
	"links": [],
	"maxDataPoints": 3,
	"nullPointMode": "connected",
	"pieType": "pie",
	"strokeWidth": 1,
	"targets": [{
		"bucketAggs": [{
				"fake": true,
				"id": "4",
				"query": "*",
				"settings": {
					"filters": [{
						"query": "dwellTime:>1000"
					}]
				},
				"type": "filters"
			},
			{
				"fake": true,
				"id": "3",
				"query": "*",
				"settings": {
					"filters": [{
							"label": "Children",
							"query": "age: <15"
						},
						{
							"label": "Young",
							"query": "age: > 15 AND age: <35"
						},
						{
							"label": "Adult",
							"query": "age: > 35, age: <50"
						},
						{
							"label": "Senior",
							"query": "age: >50"
						}
					]
				},
				"type": "filters"
			},
			{
				"field": "@timestamp",
				"id": "2",
				"settings": {
					"interval": "auto",
					"min_doc_count": 0,
					"trimEdges": 0
				},
				"type": "date_histogram"
			}
		],
		"metrics": [{
			"field": "age",
			"id": "1",
			"meta": {},
			"settings": {},
			"type": "count"
		}],
		"query": "deploy:comonext",
		"refId": "A",
		"timeField": "@timestamp"
	}],
	"title": "Age",
	"type": "grafana-piechart-panel",
	"valueName": "total"
}`

**Comment by marefr** [comment]
Copied to dashboard on play.grafan.org and changed to Grafana Test Data datasource. Working as expected, see [demo](https://play.grafana.org/d/AO7AU_vmz/pie-chart-153?orgId=1).

**Comment by rafael796** [comment]
Hello, I also have the same problem.
My grafana is v6.4.1 and pie chart is v.1.3.9.
![image](https://user-images.githubusercontent.com/57506090/68429687-52d61600-018d-11ea-8587-a1946bd5c91d.png)

**Comment by rafael796** [comment]
{
  "datasource": null,
  "aliasColors": {},
  "breakPoint": "50%",
  "cacheTimeout": null,
  "combine": {
    "label": "Others",
    "threshold": 0
  },
  "fontSize": "80%",
  "format": "short",
  "gridPos": {
    "h": 6,
    "w": 11,
    "x": 7,
    "y": 19
  },
  "id": 44,
  "interval": null,
  "legend": {
    "percentage": true,
    "show": true,
    "values": true
  },
  "legendType": "Under graph",
  "links": [],
  "maxDataPoints": 3,
  "nullPointMode": "connected",
  "options": {},
  "pieType": "pie",
  "pluginVersion": "6.4.1",
  "strokeWidth": 1,
  "targets": [
    {
      "alias": "",
      "groupBy": [
        {
          "params": [
            "status"
          ],
          "type": "tag"
        }
      ],
      "measurement": "iis_log",
      "orderByTime": "ASC",
      "policy": "autogen",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "sourceip"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "count"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=",
          "value": "SWAP2211"
        }
      ]
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Http Status",
  "type": "grafana-piechart-panel",
  "valueName": "total"
}

**Comment by rvanteru** [comment]
Even i faced similar issue but it has been fixed now by uninstalling a graph-compare-panel plugin was causing this issue for me. please see this open issue https://github.com/AutohomeCorp/graph-compare-panel/issues/7 . Please cross check your last deployed plugins.

Now pie charts works as expected.
