### ISSUE TITLE
Multiple type pie charts add donut inner circle to pies

### ISSUE THREAD

**Issue by kroppt** [grafana/piechart-panel#155]
**What Grafana version are you using?**
v5.1.4
**What datasource are you using?**
InfluxDB
**What did you do?**
Make multiple pie charts with different display options (pie and donut)
**What was the expected result?**
Each render normally
**What happened instead?**
The pie rendered with an extra ring

Pie style (messed up):
![image](https://user-images.githubusercontent.com/14015672/42900745-3c3fa3d2-8a8f-11e8-9dba-47410c4fc206.png)

Donut style (correct):
![image](https://user-images.githubusercontent.com/14015672/42900787-5cee6938-8a8f-11e8-81bd-535d501d47b8.png)

The ring gets added when mousing over the pie after adding the donut.

Should have the latest version of the plugin... I used the Grafana CLI to add it just this week.

**Comment by Rohlik** [comment]
Same problem here with datasource elasticsearch, Grafana 4.6.5 and plugin version 1.3.3.

**Comment by alexanderzobnin** [comment]
Found that it's a `flot.pie` plugin issue. Pushing a fix to Grafana.

**Comment by daniellee** [comment]
That fix has been merged in Grafana master and will be released in Grafana 6.0 (first beta release next week and full release in 3 weeks time).
