### ISSUE TITLE
t.replace is not a function 

### ISSUE THREAD

**Issue by linkypi** [grafana/piechart-panel#164]
TypeError: t.replace is not a function
![image](https://user-images.githubusercontent.com/4386639/50288356-ab7ec080-04a0-11e9-9a03-ff3657077886.png)

**Comment by janeunbi** [comment]
Did you solve this problem? I have the same problem. It used to work well suddenly, I faced this problem.

**Comment by briangann** [comment]
this appears to be a bug in the zabbix-app and not with piechart-panel
