### ISSUE TITLE
color picker is not working in grafana 5.4.2 version

### ISSUE THREAD

**Issue by 83104101Double108121** [grafana/piechart-panel#165]
It  seems  that color picker isn't working when I update grafana to 5.4 and i also update the pie chart plugin

When I click icon to change color, It appears below situation.
![pie](https://user-images.githubusercontent.com/10937328/50875366-f1c1a280-1402-11e9-87c0-fc0e536b54d2.jpg)

**Comment by kkruzich** [comment]
I came here to say the same. Grafana version 5.4.2, plugin 1.3.4. The issue is similar to https://github.com/grafana/piechart-panel/issues/115
