### ISSUE TITLE
Pie Chart is tiny

### ISSUE THREAD

**Issue by da3dsoul** [grafana/piechart-panel#166]
![chrome_2019-01-23_04-43-13](https://user-images.githubusercontent.com/5205810/51598004-9dbac180-1eca-11e9-82a6-411c1c9b4afd.png)
The pie chart isn't scaling properly. The zoom is normal, the chart has plenty of space. It renders a reasonable size when you "view" it.

I've gotten it to render nicely in vertical legend mode, so I think it's a padding math issue in horizontal mode.

I'm on the latest version that downloads when you install via grafana cli. I think that is 1.3.4, but I don't know how to check the version.

**Comment by torkelo** [comment]
What version of Grafana are you using?

**Comment by da3dsoul** [comment]
I was on 3.1.1. I updated when I noticed. I'll try it again after updating to the new version of this, as well.

**Comment by da3dsoul** [comment]
It appears to be fixed. I don't know what fixed it, but I didn't even realize that my docker compose was locking grafana to an ancient version. Now that's up to date.
