### ISSUE TITLE
v1.3.5 - perfectScrollbar.default is not a constructor

### ISSUE THREAD

**Issue by Paul-Reed** [grafana/piechart-panel#170]
Previously had v1.3.4 installed, and worked fine.
I've updated to v1.3.5 this evening, and get the error;

![pie](https://user-images.githubusercontent.com/973580/52449470-65082280-2b2f-11e9-9b6d-86ee186fadda.png)

I'm using Grafana v5.4.2 on Raspberry Pi 3B+ running Raspbian Stretch

**Comment by briangann** [comment]
rolling out 1.3.6 now with the correct output format.

**Comment by briangann** [comment]
thanks for the feedback @Paul-Reed !
