### ISSUE TITLE
Now support grafana 6.0?

### ISSUE THREAD

**Issue by night1008** [grafana/piechart-panel#174]

**Comment by jacobwilsonnet** [comment]
It doesnt seem to work on 6.0

**Comment by night1008** [comment]
@jacobwilsonnet hello, I have a try on pie chart, it works

```sql
SELECT  now() as time,  col1, count(1)
FROM  table
GROUP BY col1
```

**Comment by torkelo** [comment]
what is the problem in 6.0? pie chart only works with time series data right now
