### ISSUE TITLE
Add option for color picker for piechart  

### ISSUE THREAD

**Issue by ashimloves** [grafana/piechart-panel#18]
Kindly add option to specify color for data in piechart.
e.g. if I want to show system RAM usage in a pie chart as 3 segments - used, cached, free
then I can choose color for used as red, cached as gray, free as green. etc.

**Comment by ashimloves** [comment]
Adding sample image from line chart color picker.
![grafana2](https://cloud.githubusercontent.com/assets/3369047/13028555/5f0b90b2-d298-11e5-8352-6012f3af0d61.png)

**Comment by hminnnn** [comment]
![image1](https://user-images.githubusercontent.com/8623960/32817348-1576352a-c9f8-11e7-9602-9878355d8cd1.JPG)

May i know if the colour picker is working?

**Comment by gorkagal1983** [comment]
is the color picker working?

![piechart](https://user-images.githubusercontent.com/16732023/33329489-fb6be494-d45c-11e7-8d6c-ea026db156d7.png)

**Comment by hpcfan** [comment]
The color picker isn't working for me. I am using Firefox on a Linux workstation.
