### ISSUE TITLE
can not use in new version of grafana

### ISSUE THREAD

**Issue by mikelaowang** [grafana/piechart-panel#183]
when use piechart in 6.2.5 version  it is black and tell me 
Panel with id 6 not found

**Comment by briangann** [comment]
investigating

**Comment by briangann** [comment]
strange, it worked during testing on all version v4+, and now throws errors. Will either unpublish or fix over the next hour.

**Comment by briangann** [comment]
v1.3.8 published to fix this problem, and verified on a clean system
