### ISSUE TITLE
Panel plugin not found : grafana-piechart-panel

### ISSUE THREAD

**Issue by Xavier59** [grafana/piechart-panel#188]
Hello,

I would like to report a bug :

- Grafana Version : Grafana v6.3.2  (docker image)
- PieChart version : 1.3.8

Image of the problem : 
![](https://aws1.discourse-cdn.com/standard14/uploads/grafana/optimized/2X/a/a6e42c37ec64230347a64d60064cc6bd39b5acf7_2_690x386.png)
While googling, I found another user with the same problem : https://community.grafana.com/t/panel-plugin-not-found-grafana-piechart-panel/16953

I'm using docker and i'm importing other plugins (mouting volumes in /var/lib/grafana/plugins).
It works well but not for PieChart.

Thanks.
Xavier

**Comment by Orabig** [comment]
I had the exact same issue, and managed to find a solution.
The install procedure with "git clone" seems wrong. The 'master' branch do not own the necessary "dist" folder, thus we should use the `release-1.3.8` branch.

The command should look like :

```
git clone https://github.com/grafana/piechart-panel.git --branch release-1.3.8
```

**Comment by Xavier59** [comment]
Indeed, master since to be missing this folder.

**Comment by ryantxu** [comment]
That is intentional ;)

On master, you can build the plugin.  Or you could checkout from a released branch that includes the `dist`.  Or use the grafana-cli to checkout the official one

I just added #18671 to show a better error

**Comment by kjschnei001** [comment]
I was able to reproduce this error with Grafana v6.3.2 and grafana-piechart-panel v1.3.8, using the grafana cli to install:
`grafana-cli plugins install grafana-piechart-panel 1.3.8`

![image](https://user-images.githubusercontent.com/13695322/64184814-ab0d3680-ce31-11e9-9d1f-ef7d0b990457.png)

**Comment by brianbaker** [comment]
In case anyone makes the same mistake I did...  I downloaded the release.zip, extracted it, and committed it to our internal repo for deployment to our servers.  I didn't realize at the time that the `.gitignore` contained in the release download was ignoring the `dist` folder so that was never deployed to our servers.  I had to manually edit the `.gitignore` so that dist would be included.

**Comment by briangann** [comment]
good reminder for us to change the release process to exclude that file too!

I'll open another issue to track it.
