### ISSUE TITLE
Pie Chart not displaying (6.4.3)

### ISSUE THREAD

**Issue by zeppmg** [grafana/piechart-panel#205]
Since I've upgraded Grafana to v6.4.3, Pie Chart doesn't display anymore, whereas legend still show correctly.
Query is still correct : if I choose another visualization plugin everything works fine.
![pie-chart](https://user-images.githubusercontent.com/57366230/68310549-8131f380-00b0-11ea-9ab4-fadce7306e99.png)

**Comment by mrafieee** [comment]
I have the same problem.

**Comment by mrafieee** [comment]
upgraded the piechart to 1.3.9 and downgraded the grafana to 6.4.2, it started working.

**Comment by briangann** [comment]
investigating this now

**Comment by gjemp** [comment]
have same problem  grafana 6.4.4 but
form old times I have there i pie chart installation of version 1.3.6  and it stayed there even when i was using cli upgrade/install /downgrade so cli plugins ls showed me two installations of version 1.3.6 .

**Comment by zeppmg** [comment]
Hi @briangann ,
Any news ? Still stuck here ...
Thanks in advance.
Regards,

**Comment by digrich** [comment]
I am also observing the same issue with grafana 6.4.3

**Comment by digrich** [comment]
After upgrading pie-chart to latest version, it's working fine on 6.4.3.

**Comment by zeppmg** [comment]
same here, thanks for the update

**Comment by gjemp** [comment]
works also on 6.5.1 . In mu case it was the host dir permissions :) I deploy plugins with ansible and it run the cli command with root and due that the dir  and its content was created with root owner groups and grafana did not have access to load it.  Figured out this when i enabled debug logging in grafana :)

**Comment by nk-fouque** [comment]
@gjemp Thanks for your diagnostic, I think I might have the same problem, but how do you change those permissions ?

**Comment by gjemp** [comment]
@nk-fouque , you need to change the file and directory ownership on the host machine  via command line .
