### ISSUE TITLE
Plugin are not showing while creating dashboard

### ISSUE THREAD

**Issue by Supposethat4** [grafana/piechart-panel#214]
I have installed some plugins to use it for plotting data . These plugins are showing in plugin folder but not in dashboard while selecting visualization .  Please see images
![Screenshot (71)](https://user-images.githubusercontent.com/59995665/72616911-b16ffb00-3959-11ea-9f7c-69d5b1994a48.png)
![Screenshot (72)](https://user-images.githubusercontent.com/59995665/72616912-b16ffb00-3959-11ea-955d-0920d735124b.png)

**Comment by komajaro** [comment]
Hello
What plugin version are you using ?
I upgraded to grafana 6.5.3 and (piechart plugin v1.3.6) and I have the same issue

**Comment by Supposethat4** [comment]
I'm using Grafana  (grafana-6.5.2.windows ) and upgraded version of plugins.

**Comment by Supposethat4** [comment]
Issue has been resolved . Can you see list of plugins in plugin folder? If Yes then which Os are you using? and share your command so i will help you.

**Comment by baruchih10** [comment]
on which panel version was this resolved?

‫בתאריך יום ג׳, 21 בינו׳ 2020 ב-13:20 מאת ‪Supposethat4‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Supposethat4** [comment]
This issue was just a misunderstanding. Actually i have two folders with the name of grafana in different directory . After reading log files i was able to resolved this issue.
