### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by karma1911** [grafana/piechart-panel#22]
Hi there,

As far as I know, it seems we can't change the colors of the pie chart, as we can do in any other graphs. Any way to add this feature ?

**Comment by dotromain** [comment]
+1

**Comment by jbonet** [comment]
+1 here

**Comment by ronnykwon** [comment]
+1

**Comment by digrich** [comment]
+1

**Comment by bergquist** [comment]
Closing this since its a dupe of https://github.com/grafana/piechart-panel/issues/18

**Comment by xlash** [comment]
+1

**Comment by lucas-matt** [comment]
+1
