### ISSUE TITLE
Piechart-panel installation

### ISSUE THREAD

**Issue by ravibhooshan** [grafana/piechart-panel#25]
Hi - I have installed latest Grafna 3 beta from grafana.org but not seeing anything in /var/lib/grafana/plugins folder.

Wheni ran install commnd i got belwo error - anyhelp please:

# grafana-cli plugins install grafana-piechart-panel

Error: could not find plugin named "grafana-piechart-panel"

NAME:
   Grafana cli plugins install - install <plugin name>

USAGE:
   Grafana cli plugins install [arguments...]

**Comment by daniellee** [comment]
Can you try this:

```
grafana-cli --repo "https://grafana.net/api/plugins" plugins install grafana-piechart-panel
```

Although the command you executed should work.

**Comment by ravibhooshan** [comment]
Thanks Daniellee.. I reinstalled it and it worked.
