### ISSUE TITLE
Field Name Missing on Pie chart table

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/piechart-panel#26]
Hi,

PieChart plugin looks good, Is it possible to add field name above table values?
Its so confusing right now what values the pie chart and tables showing.

Attached is the snapshot of the same

![image](https://cloud.githubusercontent.com/assets/15123322/14349438/aafda970-fce0-11e5-889c-b87442a4e76d.png)

Thanks in advance!!

**Comment by digrich** [comment]
I assume, pie chart value is always current. It would be great to have the option to select min/max/avg/current/total as we have in singlestat panel.

**Comment by bergquist** [comment]
Singlestat does not have any legend values. But you can select how you want the values for the piechart to be calculated. That's something that should be added to this panel. Not sure any other legend value then current makes any sense for this panel.

**Comment by digrich** [comment]
@bergquist I was trying to refer reducing functions which are available under Options tab in the singlestat panel for the big value calculation. And I think you are also referring about the same thing.

**Comment by Himanshu-pupneja** [comment]
@bergquist, Any plan when table headings will be added in Pie chart, its so confusing which value it is showing untill/unless we go to edit menu and see what check box is selected.

**Comment by Ijin08** [comment]
This has been fixed.
