### ISSUE TITLE
unable to get count of documents in pie chart

### ISSUE THREAD

**Issue by kramach1980** [grafana/piechart-panel#27]
I recently added the pie chart plugin in grafana. I have noticed an issue with it and would like to know if its my configuration or a real issue.

I read documents from elasticsearch by querying the index. If i have a graph that displays a bar for each document received, i get the right data. However, when i try to create a pie chart for total number of documents received, i see that it gets reset after about 15-20 mins even though i set the time to for ex: past 1 hour. The config is as follows:

Metric => SUm of count
Group by ==> Terms ==>passOrFail (This is a term in my ES document) which indicates if the document indicates a pass or a fail
Then by ==> Date Histogram ==>@timestamp

Any idea what could be happening?

**Comment by bergquist** [comment]
The piechart, like singlestat panel will only show the last numbers in the result. So my first guess is that the query is causing problems.

have you set any interval? If you want a total count for the dashboard time you have to set interval to the same value.

**Comment by kramach1980** [comment]
Great. I had interval set to auto. I assumed it will pick up the interval
from the TIme Picker. So, if i set the time picker to 1 hr, it will set the
pie chart to 1h. Looks like, we have to set the interval in the pie chart
to 1d. And then if we choose time picker, it adjusts it accordingly. Is
this a bug by any chance?

**Comment by torkelo** [comment]
the time range used for the query is the one picked in the dashboard time picker (unless panel time range override is specified).

If you want totals in the pie chart panel make sure your date histogram interval is very high (like 1y) , that way the query will always return only 1 data point
