### ISSUE TITLE
nothing getting displayed on the chart, just shows blank

### ISSUE THREAD

**Issue by mamtaed8811** [grafana/piechart-panel#276]
I have a sample data that's coming from a sql query in the table type format
site, device_count
sjc1,25
sjc2,1200
cbg1,1000
cbg2,500

I have tried the latest version(1.6.1 as well as 1.5.0) with Grafana 7.5.3 and 7.4.3 but it just shows blank. Doesn't give me any option to pick the columns or anything. 
<img width="1440" alt="Screen Shot 2021-05-11 at 8 52 28 AM" src="https://user-images.githubusercontent.com/28987826/117846393-3e695280-b236-11eb-98f1-29e530135859.png">

**Comment by mamtaed8811** [comment]
My production Grafana server is 7.4.3 and pie chart panel
<https://grafana.com/docs/grafana/latest/panels/visualizations/pie-chart-panel/>
isn't available for that version as of what I know. What are my options?
Also, sorry about tagging other people as I didn't know that tagging would
be considered scam.

Thanks

**Comment by oddlittlebird** [comment]
I recommend asking on community.grafana.com. I'm sorry, I'm just not familiar enough with the older functionality to be helpful.
