### ISSUE TITLE
[Question] Data as "reference"

### ISSUE THREAD

**Issue by matthgyver** [grafana/piechart-panel#29]
Hi,

I'd like to repport NAS usage as pie chart.
I've 2 datas : space used and quota. (have'nt free space information and can't calculate it from data source :-/)
I'd like to build a pie chart that represent space usage in report with quota.
So quota is full pie chart if space used is 0% and pie chart is divide in 2 if space used is 50% by example. 
Is it possible please ?

Thank you

**Comment by bergquist** [comment]
Then your datasource have to be able to subtract the values of serie 1 from 2. Grafana it self doesn't do any calculations for time series.
