### ISSUE TITLE
Option to show percentage on table legend

### ISSUE THREAD

**Issue by diogouchoas** [grafana/piechart-panel#32]
It would be very useful to have an option to show percentage values instead of count on the table legend.
![image](https://cloud.githubusercontent.com/assets/1450345/15237204/1d6d5a00-18a2-11e6-9ef9-c79bd1b156a8.png)

**Comment by abcfy2** [comment]
I've upgraded to `1.1.4`, but the `show percentage` seems not working.
![qq 20161127235914](https://cloud.githubusercontent.com/assets/5327677/20649557/99c5ca7c-b4fd-11e6-87c9-253688caa873.png)

@mpchadwick

**Comment by Ijin08** [comment]
This is fixed with pr #41.
