### ISSUE TITLE
Legend overlaps with graphs

### ISSUE THREAD

**Issue by Didainius** [grafana/piechart-panel#34]
Legend overlaps with graph when going to dashboard (first picture). If I zoom in on that graph (clicking on the title and then view) and then go back it is showing nice as on the second picture.
Simple refresh (using top right button) solves the issue on all piecharts in the dashboard.
Grafana is 3.0.2.
Pie Chart is 1.1.1

![correct](https://cloud.githubusercontent.com/assets/15804230/15538632/227071b6-2286-11e6-8c9a-40a1a79762e6.PNG)
![wrong](https://cloud.githubusercontent.com/assets/15804230/15538633/228895f2-2286-11e6-8c59-be01b80a256f.PNG)

**Comment by vitorboschi** [comment]
+1

**Comment by LuboVarga** [comment]
+1 (editing panel, increasing/decreasing its size fixes placement of graph, but reloading dashboard causes to make it bad again)

**Comment by digrich** [comment]
+1

**Comment by Raniz85** [comment]
+1

**Comment by mjtnajafi** [comment]
+1

**Comment by IgorGrizzzly** [comment]
+1

**Comment by smalik03** [comment]
This issue is also present in the graph panel, there is a temporary fix in it though, It renders the graph again after a timeout.

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.ts#L332
