### ISSUE TITLE
Now showing data in Piechart !

### ISSUE THREAD

**Issue by gugansankar** [grafana/piechart-panel#39]
no data showing in piechart. but same data can be seen in kibana4. Not sure whether I made any mistake in configuration. Please someone help.

Docs value shows : NaN
![gf5](https://cloud.githubusercontent.com/assets/4958813/16259525/b9cc2bbc-3880-11e6-9516-94a4ab626cc1.png)

Kibana log:  [ data shows here]
![kb5](https://cloud.githubusercontent.com/assets/4958813/16259526/b9d09bf2-3880-11e6-9aa8-ddd0e83e9db3.png)

**Comment by gugansankar** [comment]
Any chance to check this ?

**Comment by kinhunt** [comment]
same here

**Comment by bergquist** [comment]
Please use a date histogram as well. ref https://github.com/grafana/piechart-panel/issues/46
