### ISSUE TITLE
PieChart don't resolve template variables in series name ?

### ISSUE THREAD

**Issue by rterrettaz** [grafana/piechart-panel#40]
Hello everybody,
I have a dashboard with a Zabbix source, and a variable in templating "$branche"
I created a pie that shows this variable. it works. 
But I want to display the variable "$branche" : in the legend, it display "$branche" and not the name of the branch. Same in the tooltip.
it's a bug or I make a mistake? Thank you very much in advance for your reply.

![image](https://cloud.githubusercontent.com/assets/20288589/16569672/52d96ee8-4239-11e6-8110-1bbb2d304a96.png)

**Comment by gretamosa** [comment]
AFAIK template variables are not supported in this plugin. However, it doesn't make much sense because your variable "translation" will apply to all elements in your chart / query / metric. Maybe you look forward to value mapping translation?

**Comment by bergquist** [comment]
This should be supported by the datasource. Not the panel
