### ISSUE TITLE
Values in legend are displayed raw, not with the correct unit

### ISSUE THREAD

**Issue by Fox32** [grafana/piechart-panel#51]
When selecting a unit for the numeric metrics, only the tooltip uses this unit. Values in legend are displayed as the raw value which makes them hard to read. See attached screenshot.

![image](https://cloud.githubusercontent.com/assets/648527/19112459/36c0add8-8b05-11e6-82ca-371697fcea91.png)

Grafana Version:  v4.0.0-pre1 (commit: 92121ea)
Plugin Version: 1.1.1

**Comment by daniellee** [comment]
Fixed by #66
