### ISSUE TITLE
Pie Legend bytes to MiB

### ISSUE THREAD

**Issue by Michsh** [grafana/piechart-panel#54]
Pie legend dosen`t convert from bytes to MiB. Mouseover Pie convertion works.

![pielegend](https://cloud.githubusercontent.com/assets/8654261/20601656/6467c350-b262-11e6-8aeb-ae8a08721f9f.png)

**Comment by xiaoxue999** [comment]
+1 all of Unit can not be change....

**Comment by fredprod** [comment]
+1

**Comment by conet** [comment]
This is a duplicate of issue #51, fixed by PR #66.
