### ISSUE TITLE
Donut chart  display as pie-chart after checking on Transparent checkbox

### ISSUE THREAD

**Issue by Venu4thFeb** [grafana/piechart-panel#56]
After creating a basic pie chart.
Steps to recreate the issue:-
1. In option tab,select the Type as donut from the drop down present .
2. In general tab, check the transparent checkbox.
3.close the edit section (after saving).

-Donut chart will be displayed as Pie chart

Note:-Am using grafana 3.1.0 for 64 bit windows

i think enabling transparent checkbox (in general tab) is causing the donut chart to display as pie chart.

**Comment by jenrg** [comment]
Same here, I'm using Grafana v4.1.2 running on Ubuntu 16.04.2 LTS. Viewed with Firefox 51.0.1 on 64-bit Windows 10

**Comment by lucasrodcosta** [comment]
Same here.  
I just opened the PR #70 to handle this issue.
