### ISSUE TITLE
Compatible with grafana 4.x

### ISSUE THREAD

**Issue by haihq88** [grafana/piechart-panel#60]
Please help to make it works with grafana 4.x (grafana-4.1.1-1484211277.x86_64)
Thanks a lot

**Comment by sd65** [comment]
Hi,

With Grafana 4.2.0 I managed to install and use piechart panel without problems.
I had to update the Zabbix App plugin before to make it works though.

**Comment by daniellee** [comment]
It works with Grafana 4.x. Can you describe the error you are getting @haihq88 ?

**Comment by SimenB** [comment]
The deployed readme should probably be updated

![image](https://cloud.githubusercontent.com/assets/1404810/26351740/1c87f4e4-3fb9-11e7-9673-96bf3a2a4108.png)
