### ISSUE TITLE
Bug with decimal value on pie 

### ISSUE THREAD

**Issue by Azurrrr** [grafana/piechart-panel#69]
I created a pie chart with four metrics
It constained 0|0|0.44|99.56 (Sum == 100%) 
The legend showed this: 
![image](https://cloud.githubusercontent.com/assets/6927848/25482957/5489c666-2b6d-11e7-848c-15474a11799a.png)
The pie showed 
![image](https://cloud.githubusercontent.com/assets/6927848/25483034/98a2d702-2b6d-11e7-8ca8-c746fde73881.png)
![image](https://cloud.githubusercontent.com/assets/6927848/25483078/cdf629ae-2b6d-11e7-876e-8b97aae876e1.png)
data from influxdb 
![image](https://cloud.githubusercontent.com/assets/6927848/25483320/b7a34474-2b6e-11e7-9e6c-0d7d000f7379.png)

**Comment by daniellee** [comment]
It gets the auto rounding. For the SingleStat panel there is a decimals fields that allows you to control this. We should add this for Piechart too.

SingleStat options:

![image](https://cloud.githubusercontent.com/assets/434655/25888481/a2bdc1fe-3566-11e7-9f7f-88470806d0b5.png)
