### ISSUE TITLE
Provide alternative title for values in legend

### ISSUE THREAD

**Issue by cross** [grafana/piechart-panel#81]
I have a number of pie charts, and the values in my data are "points".  Not a unit of measure, or anything else supported in units, they're just shorts.  But, I want that value described as points.  In bar/line graphs, this is accomplished by a custom Y axis label.

Could you provide a mechanism that when "Legend Values" is on, so that the values appear in the legend, and alternative title for that column can be specified?  Default to "values", but editable in the panel config.

**Comment by scjoiner** [comment]
+1

**Comment by cross** [comment]
Any chance this can be reviewed for potential inclusion?  Prioritized?  Thanks...

**Comment by Diegonarducci88** [comment]
+1

**Comment by pol-alex** [comment]
@Ijin08 Is https://github.com/grafana/piechart-panel/commit/4b6d83e4c57f92034cb022a8aaafa4b83e56c336 commit add ability to change value? I still unable to change value for MSSQL datasource
