### ISSUE TITLE
Legend value reporting as NaN.nfinity

### ISSUE THREAD

**Issue by geneguvo** [grafana/piechart-panel#84]
Hi,
Whenever a value becomes zero, the pie-chart legend is showing "NaN.nfinity" (see img below).

It seems the bug comes when the value is re-formatted to display in the corrected unit: https://github.com/grafana/piechart-panel/commit/3b6533473c3179c62866dbdaa8799ab08f2707dc

Once I removed the above change it shows up "0" as expected, but changing units take no effect on the displayed legend value.

I'm using grafana 4.3.2, and the pie-chart plugin version 1.1.5.

Regards,
Diego.

![screen shot 2017-08-18 at 16 17 36](https://user-images.githubusercontent.com/1673745/29462868-091c61c6-8431-11e7-8c6f-d50371c80ef9.png)

**Comment by suyogdilipkale** [comment]
I see the same issue, any fix for this?

**Comment by scjoiner** [comment]
+1 on our end. Our calculation is something like "72-count(X)" which should normally be 0, but shows up as NaN.nfinity.

**Comment by Diegonarducci88** [comment]
when fix ?

**Comment by alkalinecoffee** [comment]
A possible workaround for the time being: adjust your query to include only values greater than zero, ie (prometheus) `http_request_duration_seconds_count > 0`
