### ISSUE TITLE
 Add "No data points" description for pie chart with 0 value.

### ISSUE THREAD

**Issue by selina2017** [grafana/piechart-panel#86]
https://github.com/grafana/grafana/issues/9188

I opened issue 9188 on grafana/issues but should have opened here.
What Grafana version are you using?
Grafana version 4.4.3
What datasource are you using?
InfluxDB
What OS are you running grafana on?
ubuntu
What did you do?
Our pie chart is to show abnormal behavior for a site. If there is no error (value = 0), the pie chart is showing blank. However, it is misleading to users who are not sure whether there is error that prevent the data from showing or there is no data.
<img width="186" alt="30140649-f5d15ef6-932a-11e7-91fc-75662ea9d7c7" src="https://user-images.githubusercontent.com/31295632/30722748-c5d6c6fa-9ee7-11e7-8fda-ec4c2e1f4bf9.png">

When there is data, the pie chart is looking fine.
<img width="264" alt="30140600-9641d826-932a-11e7-8579-530c9d7a7b22" src="https://user-images.githubusercontent.com/31295632/30722775-dd4c60a6-9ee7-11e7-800e-51eeaf50f79a.png">

What was the expected result?
The pie chart should show "No data points" just like what is shown in bar graph.
<img width="546" alt="30140457-a497d8fe-9329-11e7-87b0-94a84143b929" src="https://user-images.githubusercontent.com/31295632/30722796-eee3089c-9ee7-11e7-9dd7-16d87f539cb6.png">

What happened instead?
The pie chart is showing blank.
<img width="186" alt="30140651-fae05a96-932a-11e7-8029-e687bca1ebd0" src="https://user-images.githubusercontent.com/31295632/30722812-fb6ccaa8-9ee7-11e7-8564-b4c50dbc29e1.png">

**Comment by Diegonarducci88** [comment]
+1
