### ISSUE TITLE
ElasticSearch 5.x Group by Terms error (length not defined)

### ISSUE THREAD

**Issue by lfdominguez** [grafana/piechart-panel#95]
Hello, I push ntopng data directly into ElasticSearch and i want see some graphics of that information, like the Layer 7 Protocols... well.... When i add the PieChart pannel and select the query 

![image](https://user-images.githubusercontent.com/5604131/31556830-9316b822-b014-11e7-9571-1956afa03f4c.png)

![image](https://user-images.githubusercontent.com/5604131/31556861-b1c7b6fe-b014-11e7-8412-832dbafd89c6.png)

The response of elasticsearch is:
`{
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/9/_msearch",
    "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"ntopng-*\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1507891196845\",\"lte\":\"1507912796845\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}}]}},\"aggs\":{\"2\":{\"terms\":{\"field\":\"L7_PROTO_NAME.raw\",\"size\":10,\"order\":{\"_term\":\"desc\"},\"min_doc_count\":1},\"aggs\":{}}}}\n"
  },
  "response": {
    "responses": [
      {
        "took": 3,
        "timed_out": false,
        "_shards": {
          "total": 5,
          "successful": 5,
          "failed": 0
        },
        "hits": {
          "total": 125024,
          "max_score": 0,
          "hits": []
        },
        "aggregations": {
          "2": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 86260,
            "buckets": [
              {
                "key": "Yahoo",
                "doc_count": 4
              },
              {
                "key": "Unknown",
                "doc_count": 459
              },
              {
                "key": "Unencrypted_Jabber",
                "doc_count": 196
              },
              {
                "key": "SSL_No_Cert",
                "doc_count": 19188
              },
              {
                "key": "SSL.HTTP",
                "doc_count": 1
              },
              {
                "key": "SSL",
                "doc_count": 4034
              },
              {
                "key": "SSH.HTTP",
                "doc_count": 1
              },
              {
                "key": "SSH",
                "doc_count": 865
              },
              {
                "key": "SSDP",
                "doc_count": 98
              },
              {
                "key": "SMTPS",
                "doc_count": 12
              }
            ]
          }
        },
        "status": 200
      }
    ]
  }
}`

**Comment by manojown** [comment]
actually, grafana support only time series data so you need to select date histogram with  @timestam field then you can view your graph or pie whatever
![helpgithub](https://user-images.githubusercontent.com/24589611/31558347-1f4e7ec4-b06a-11e7-85bc-703bce8bc857.png)
i hope this will help you .

**Comment by lfdominguez** [comment]
Thanks, that's help, but see this, dont show any count.

![image](https://user-images.githubusercontent.com/5604131/31559140-9a95ea2e-b01d-11e7-8fc9-3022fc88859e.png)

**Comment by lfdominguez** [comment]
The elasticsearch returns into aggregations the field "doc_count" with good values.

**Comment by lfdominguez** [comment]
sorry, my bad... i need to set "All" Into value of the options. Thanks @manojown now is working great!!!

**Comment by wuqinlong** [comment]
I want a pie-chart with auditbeat data
the query is ok in table, like this
<img width="960" alt="table_20190605201917" src="https://user-images.githubusercontent.com/6110294/58955955-d0a58800-87cf-11e9-9649-b44cf2c717f5.png">

but `Cannot read property 'length' of undefined` in pie-chart
<img width="960" alt="pie_20190605201855" src="https://user-images.githubusercontent.com/6110294/58955997-e450ee80-87cf-11e9-8f34-60f0f0cc4785.png">
