### ISSUE TITLE
Bug with 1.0 and 5.0 value in legend

### ISSUE THREAD

**Issue by hrochniak** [grafana/piechart-panel#98]
Hi!

When I have value with number 1 or 5, in legend it always show as 1.0 and 5.0. There is not issue with any other value, see screenshot below. I am using newest beta version of Grafana - v4.6.0-beta2 and newest available version of Pie Chart plugin - 1.1.5. As data source I am using MySQL database. I am adding also output from query issued via SQL in phpmyadmin to be sure there is not issue with MySQL outputs. 

Am I doing something wrong or is it bug in Pie Chart? :)

![image](https://user-images.githubusercontent.com/7081197/31814447-f0d41070-b589-11e7-8943-2e9462f90fd9.png)
![image](https://user-images.githubusercontent.com/7081197/31814672-a5e55fc8-b58a-11e7-9d91-7dfdb795c1b1.png)

**Comment by itayB** [comment]
@hrochniak can you add the SQL query that generated this chart?
